config-version: 1.0


# $$$$$$\ $$\   $$\ $$$$$$$$\  $$$$$$\
# \_$$  _|$$$\  $$ |$$  _____|$$  __$$\
#   $$ |  $$$$\ $$ |$$ |      $$ /  $$ |
#   $$ |  $$ $$\$$ |$$$$$\    $$ |  $$ |
#   $$ |  $$ \$$$$ |$$  __|   $$ |  $$ |
#   $$ |  $$ |\$$$ |$$ |      $$ |  $$ |
# $$$$$$\ $$ | \$$ |$$ |       $$$$$$  |
# \______|\__|  \__|\__|       \______/
#
#-----------------------------------------------------------------------------------------------------------------------------
#                                                  | 音乐选项： |
#-----------------------------------------------------------------------------------------------------------------------------
# creative, credits, disc_5, disc_11, disc_13, disc_blocks, disc_cat, disc_chirp, disc_creator,
# disc_creator_music_box, disc_far, disc_mall, disc_mellohi, disc_otherside, disc_pigstep, disc_precipice, disc_relic,
# disc_stal, disc_strad, disc_wait, disc_ward
# 警告：某些歌曲仅在特定版本中可用！！！
#-----------------------------------------------------------------------------------------------------------------------------
#                                                  | 颜色选项： |
#-----------------------------------------------------------------------------------------------------------------------------
# aqua, black, blue, gray, green, lime, orange, purple, red, silver, teal, white, 和 yellow。






#  _____  _____  _____  _____  _____  _____  __
#|   __||   __||   | ||   __|| __  ||  _  ||  |
#|  |  ||   __|| | | ||   __||    -||     ||  |__
#|_____||_____||_|___||_____||__|__||__|__||_____|

#插件常规消息选项。
messages-general:
  #管理员命令和消息的显示方式。
  admin:
    #启用或禁用管理员消息前缀。
    prefix_enabled: false
    prefix: "&7[&6Versus&7] "
    #设置管理员消息的主色调。
    primary_color: "&6"
    #设置用于融入背景的文字颜色，如确认消息。
    subtle_color: "&7"
    #设置用于突出关键文字（如玩家名）的颜色。
    highlighted_color: "&c"
    #设置重要文字（如按钮或标题）的颜色。
    bold_color: "&6&l"
    #设置所有聊天消息中线条元素的样式。
    line: "&6&m-------------------------------------"
  #错误消息的样式显示方式。
  errors:
    #设置聊天中错误消息前显示的文字和颜色。
    error_prefix: "&c错误: &4"
    no_permission_message: "你没有权限使用该命令。"
    only_players_message: "只有玩家才能使用此命令！"


#  ____   _____  _____  __     _  _____  _____
#|    \ |  |  ||   __||  |   |_||   | ||   __|
#|  |  ||  |  ||   __||  |__ | || | | ||  |  |
#|____/ |_____||_____||_____||_||_|___||_____|

#决斗行为、消息和时间设置。
dueling:
  mechanics:
    #设置是否需要 'versus.spectate' 和 'versus.duel' 权限才能观战和决斗。
    #如果为 false, 任何玩家都可以决斗。
    permission_required_to_duel: false

    #设置胜者决斗后返回的位置。
    #选项包括: 'spectate' , 'spawn' , 'previous', 和 'custom'。
    #输入其他值将默认为 'spawn'。
    #'spectate' 返回观战区域。
    #'spawn' 返回出生点。
    #'previous' 返回决斗前的位置。
    #'custom' 返回自定义位置, 在下方配置。
    return_winners: 'spectate'
    #此设置仅在 'return_winners' 设为 'custom' 时生效。
    winner_return_location:
      x: 0
      y: 0
      z: 0
      world: "world"


    #设置败者决斗后返回的位置。
    #选项包括: 'spectate' , 'spawn' , 'previous', 和 'custom'。
    #输入其他值将默认为 'spawn'。
    #'spectate' 返回观战区域。
    #'spawn' 返回出生点。
    #'previous' 返回决斗前的位置。
    #'custom' 返回自定义位置, 在下方配置。
    return_losers: 'spawn'
    #此设置仅在 'return_losers' 设为 'custom' 时生效。
    loser_return_location:
      x: 0
      y: 0
      z: 0
      world: "world"



    #设置玩家在决斗失败后是否立即复活, 跳过重生界面。
    instant_respawn: false

    #决斗中是否允许放置方块。
    allow_block_placements: true
    #决斗中是否允许破坏方块。
    allow_block_destruction: true
    #设置决斗开始前的倒计时时间(秒)。
    countdown_duration: 5
    #决斗期间被禁用的命令列表。
    blocked_commands:
      - 'heal'
      - 'gamemode'
      - 'spawn'
      - 'kit'
      - 'tp'
      - 'tpa'
      - 'tpyes'
      - 'tpaccept'
      - 'tpahere'
      - 'etpa'
      - 'back'
      - 'eback'
      - 'return'
      - 'ereturn'
      - 'sethome'
      - 'esethome'
      - 'createhome'
      - 'ecreatehome'
      - 'espawn'
      - 'chest'
      - 'vault'
      - 'enderchest'

  #决斗期间的药水效果、烟花效果选项。
  announcements:
    #设置是否在全局聊天中公告决斗。
    announce_duels: false
    #公告决斗开始的文本。
    #在 %button% 和 %button% 之间放置玩家点击观战的文本。
    duel_start_announcement: "&c%player_one%&6 正在与 &c%player_two%&6 决斗! %button%&6&l点击此处观战.%button%"
    #公告决斗结束及胜者/败者的文本。
    duel_end_announcement: "&6恭喜 &c%winner%&6! 他刚刚赢得了与 &c%loser%&6 的比赛!"
  effects:
    #启用或禁用进入决斗时的失明效果。
    blindness_effects_enabled: true
    #启用或禁用决斗胜利后播放的效果。
    victory_effects_enabled: true
    #设置决斗胜利后效果的持续时间(秒)。
    victory_effects_duration: 10
    #启用或禁用决斗期间的所有烟花效果。
    fireworks_enabled: true
    #设置决斗期间烟花的颜色。请查看此配置文件顶部的颜色选项。
    fireworks_color: "blue"
  #决斗期间播放的音乐选项。
  music:
    #启用或禁用决斗期间的音乐。
    fight_music_enabled: true
    #设置决斗期间播放的音乐。请查看此配置文件顶部的音乐选项。
    fight_music: 'disc_far'
    #启用或禁用玩家赢得决斗后播放的音乐。
    victory_music_enabled: true
    victory_music: 'disc_pigstep'
  #决斗期间显示的聊天消息和标题(屏幕文字)选项。
  messages:
    #决斗倒计时期间在玩家屏幕上显示的文字。
    countdown_title: "&7%seconds%"
    #决斗倒计时期间发送给每个玩家的聊天消息。
    countdown_message: "&6&e%seconds%&6 秒后开始"
    #决斗开始时在玩家屏幕上显示的文字。
    duel_go_message: "&6&l开始!"
    #玩家赢得决斗后在屏幕上显示的文字。
    victory_title_message: "&6&l胜利"
    #玩家赢得决斗后屏幕上显示的副标题。
    victory_subtitle_message: "%player%"
    #玩家决斗失败复活后收到的聊天消息。
    duel_loss_message: "&6别灰心 &c%player%。"
    #观战者进入竞技场后收到的聊天消息。
    duel_spectate_message: "&7你正在观战 &6%player_one% &7和 &6%player_two% &7的决斗。"


#  _____  _____  _____  _____  _____  _____  _____  _  _____  _____
#| __  ||   __||     ||  |  ||   __||   __||_   _||_||   | ||   __|
#|    -||   __||  |  ||  |  ||   __||__   |  | |  | || | | ||  |  |
#|__|__||_____||__  _||_____||_____||_____|  |_|  |_||_|___||_____|
#                 |__|

#决斗请求的聊天消息和样式选项。
requesting:
  mechanics:
    #设置玩家是否可以通过shift点击其他玩家角色来发起决斗请求。
    shift_click_requesting_enabled: false
  messages:
    #玩家拒绝决斗请求后收到的聊天消息。
    denied_request_confirmation: "&7你拒绝了 &c%player%&6 的决斗请求&7。"
    #玩家拒绝他人决斗请求后, 对方收到的聊天消息。
    denied_request: "&c%player% &7拒绝了你的 &6决斗请求&7。"
    #玩家发送决斗请求后收到的聊天消息。
    sent_request: "&7你向 &6%player% &7发送了 &c决斗请求&7。"
    #玩家收到决斗请求时的聊天消息。
    request_notification: "&6%player% &7邀请你进行 &c决斗!"
    #玩家点击接受决斗请求的文本样式。
    accept_button: "&7&l[&a&l接受&7&l]"
    #玩家点击拒绝决斗请求的文本样式。
    deny_button: "&7&l[&c&l拒绝&7&l]"
    #没有可用竞技场时发送给玩家的聊天消息。
    no_arenas_available: "&6你已被加入队列。请等待有可用的竞技场。"
    #取消决斗队列后发送给玩家的聊天消息。
    cancel_request: "&6你已退出决斗队列。"



#  ____  _____ _____ _____ _____ ____  _____ _____ _____ _____ _____ _____
#|    \|   __|  _  |   __|   | |    \|   __|   | |     |     |   __|   __|
#|  |  |   __|   __|   __| | | |  |  |   __| | | |   --|-   -|   __|__   |
#|____/|_____|__|  |_____|_|___|____/|_____|_|___|_____|_____|_____|_____|

#(可选)
#依赖项和与其他插件或API交互的选项。
dependencies:
  placeholderAPI:
    #注意: 此功能仅在以下条件满足时有效:
    #1) Essentials 和 PlaceholderAPI 都已安装。
    #2) Essentials 已通过输入 /papi ecloud download Essentials 注册到 PlaceholderAPI。
    #否则, 此功能将被忽略, 玩家名称将保持不变。
    #设置是否用 Essentials 昵称替换 Versus 聊天消息中的玩家名称。
    essentials_nicknames_enabled: true
  itemsadder:
    #设置是否可以将自定义 ItemsAdder 物品保存到物品包中。
    items_adder_for_kits: true
